# Generated by Django 4.2.2 on 2023-07-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='website',
            field=models.CharField(max_length=100000, null=True, verbose_name='Website Address'),
        ),
    ]
