# Generated by Django 4.2.2 on 2023-07-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_recentwork_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100000, null=True, verbose_name='Project title')),
                ('image', models.ImageField(null=True, upload_to='projects')),
                ('website', models.CharField(max_length=100000, null=True, verbose_name='Website Address')),
            ],
        ),
    ]
